config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :carts
  root 'home#index'
  devise_for :users
  resources :items
  resources :charges, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :line_items, dependent: :destroy

	def add_item(item)
		    current_item = line_items.find_by(item: item)

    if current_item
      current_item.increment(:quantity)
    else
      current_item = line_items.new(item: item)
    end
    current_item
  end

  def total
  line_items.to_a.sum(&:total)
  end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
rescue_from ActiveRecord::RecordNotFound, with: :cart_not_found


  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    return unless @cart.id == session[:cart_id]
    @cart.destroy
    session.delete(:cart_id)
    respond_to do |format|
      format.html { redirect_to root_url, notice: "Votre panier est vide" }
      format.json { head :no_content }
        end
  end



private


    def cart_not_found
      redirect_to root_url, alert: t(".cart_not_found")
    end

       # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<h2>Panier</h2>
<ul>
  <% cart.line_items.each do |element| %>
    <li><%= element.item.title %> (X <%= element.quantity %>) <span class="badge badge-info"><%= number_to_currency(element.total, unit: "€", separator: ",", format: "%n %u") %>
</li>
  <% end %>
</ul>


<p class="font-weight-bold">Total : <span class="badge badge-info"><%= number_to_currency(@cart.total, unit: "€", separator: ",", format: "%n %u") %></span></p>



<div class="row">
  <div class="col">
   <%= link_to "Retour aux produits", root_path, class: "btn btn-primary" %>
  </div> 


  <div class="col">
   <%= button_to "Acheter", new_order_path, method: :get, class: "btn btn-primary" %>
  </div>
</div>



  <div class="col">
    <%= button_to "Vider le panier", @cart, method: :delete, data: {
    confirm: "Êtes-vous sûr ?" }, class: "btn btn-danger" %>
  </div>
</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<body class="background_color">
    <div class="item-show-container">
      <div class="row">
        <div class="col-lg-6">
          <h2>Panier</h2>
          <ul>
            <% @cart.line_items.each do |element| %>
              <li><%= element.item.title %> (X <%= element.quantity %>) <span class="badge badge-info"><%= number_to_currency(element.total, unit: "€", separator: ",", format: "%n %u") %>
          </li>
            <% end %>
          </ul>

          <p class="font-weight-bold">Total : <span class="badge badge-info"><%= number_to_currency(@cart.total, unit: "€", separator: ",", format: "%n %u") %></span></p>
          <br><br>

          <%= link_to "Retour aux produits", root_path, class: "btn btn-primary" %>
        </div>

        <div class="col-lg-6">
            <%= button_to "Confirmer commande", new_order_path, method: :get, class: "btn btn-primary" %><br><br>
            <%= button_to "Vider le panier", @cart, method: :delete, data: {
              confirm: "Êtes-vous sûr ?" }, class: "btn btn-danger" %>
        </div>
      </div>
  </div>
</body>